# Generated by Django 3.0.3 on 2021-06-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200314_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='roommanager',
            name='profile_pic',
        ),
    ]
